#execution
echo "Starting first shell script...";
echo "Dropout 0%";
bash execution_1.sh;
bash execution_2.sh;
bash execution_3.sh;
bash execution_4.sh;
bash execution_5.sh;
bash execution_6.sh;
bash execution_7.sh;
bash execution_8.sh;
bash execution_9.sh;
bash execution_10.sh;
bash execution_11.sh;
bash execution_12.sh;
bash execution_13.sh;
bash execution_14.sh;
bash execution_15.sh;
bash execution_16.sh;
bash execution_17.sh;
bash execution_18.sh;
bash execution_19.sh;
bash execution_20.sh;
bash execution_21.sh;
bash execution_22.sh;
bash execution_23.sh;
bash execution_24.sh;
bash execution_25.sh;
bash execution_26.sh;
bash execution_27.sh;
bash execution_28.sh;
bash execution_29.sh;
bash execution_30.sh;
echo "Ending first shell script...";