./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'APOB' 1
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'GSTA2' 2
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'ALB' 3
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'HGD' 4
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'VTN' 5
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'APOC4.APOC2' 6
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'APOC3' 7
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'GNRH2' 8
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'SULT1A2' 9
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'RBP2' 10
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'GSTA1' 11
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'AFP' 12
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'APOC2' 13
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'FGA' 14
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'APOA4' 15
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'FABP1' 16
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'RBP4' 17
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'UGT2B11' 18
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'FGB' 19
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'TTR' 20
./prog_seq 'geneNames_3.txt' 'exe_1' 'hHep' 'FGG' 21
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'APOB' 22
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'GSTA2' 23
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'ALB' 24
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'HGD' 25
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'VTN' 26
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'APOC4.APOC2' 27
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'APOC3' 28
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'GNRH2' 29
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'SULT1A2' 30
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'RBP2' 31
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'GSTA1' 32
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'AFP' 33
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'APOC2' 34
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'FGA' 35
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'APOA4' 36
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'FABP1' 37
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'RBP4' 38
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'UGT2B11' 39
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'FGB' 40
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'TTR' 41
./prog_seq 'geneNames_3.txt' 'exe_2' 'hHep' 'FGG' 42
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'APOB' 43
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'GSTA2' 44
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'ALB' 45
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'HGD' 46
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'VTN' 47
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'APOC4.APOC2' 48
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'APOC3' 49
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'GNRH2' 50
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'SULT1A2' 51
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'RBP2' 52
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'GSTA1' 53
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'AFP' 54
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'APOC2' 55
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'FGA' 56
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'APOA4' 57
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'FABP1' 58
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'RBP4' 59
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'UGT2B11' 60
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'FGB' 61
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'TTR' 62
./prog_seq 'geneNames_3.txt' 'exe_3' 'hHep' 'FGG' 63
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'APOB' 64
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'GSTA2' 65
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'ALB' 66
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'HGD' 67
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'VTN' 68
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'APOC4.APOC2' 69
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'APOC3' 70
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'GNRH2' 71
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'SULT1A2' 72
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'RBP2' 73
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'GSTA1' 74
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'AFP' 75
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'APOC2' 76
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'FGA' 77
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'APOA4' 78
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'FABP1' 79
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'RBP4' 80
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'UGT2B11' 81
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'FGB' 82
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'TTR' 83
./prog_seq 'geneNames_3.txt' 'exe_4' 'hHep' 'FGG' 84
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'APOB' 85
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'GSTA2' 86
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'ALB' 87
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'HGD' 88
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'VTN' 89
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'APOC4.APOC2' 90
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'APOC3' 91
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'GNRH2' 92
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'SULT1A2' 93
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'RBP2' 94
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'GSTA1' 95
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'AFP' 96
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'APOC2' 97
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'FGA' 98
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'APOA4' 99
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'FABP1' 100
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'RBP4' 101
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'UGT2B11' 102
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'FGB' 103
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'TTR' 104
./prog_seq 'geneNames_3.txt' 'exe_5' 'hHep' 'FGG' 105
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'APOB' 106
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'GSTA2' 107
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'ALB' 108
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'HGD' 109
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'VTN' 110
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'APOC4.APOC2' 111
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'APOC3' 112
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'GNRH2' 113
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'SULT1A2' 114
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'RBP2' 115
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'GSTA1' 116
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'AFP' 117
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'APOC2' 118
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'FGA' 119
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'APOA4' 120
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'FABP1' 121
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'RBP4' 122
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'UGT2B11' 123
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'FGB' 124
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'TTR' 125
./prog_seq 'geneNames_3.txt' 'exe_6' 'hHep' 'FGG' 126
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'APOB' 127
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'GSTA2' 128
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'ALB' 129
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'HGD' 130
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'VTN' 131
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'APOC4.APOC2' 132
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'APOC3' 133
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'GNRH2' 134
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'SULT1A2' 135
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'RBP2' 136
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'GSTA1' 137
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'AFP' 138
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'APOC2' 139
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'FGA' 140
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'APOA4' 141
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'FABP1' 142
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'RBP4' 143
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'UGT2B11' 144
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'FGB' 145
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'TTR' 146
./prog_seq 'geneNames_3.txt' 'exe_7' 'hHep' 'FGG' 147
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'APOB' 148
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'GSTA2' 149
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'ALB' 150
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'HGD' 151
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'VTN' 152
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'APOC4.APOC2' 153
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'APOC3' 154
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'GNRH2' 155
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'SULT1A2' 156
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'RBP2' 157
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'GSTA1' 158
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'AFP' 159
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'APOC2' 160
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'FGA' 161
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'APOA4' 162
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'FABP1' 163
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'RBP4' 164
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'UGT2B11' 165
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'FGB' 166
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'TTR' 167
./prog_seq 'geneNames_3.txt' 'exe_8' 'hHep' 'FGG' 168
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'APOB' 169
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'GSTA2' 170
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'ALB' 171
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'HGD' 172
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'VTN' 173
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'APOC4.APOC2' 174
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'APOC3' 175
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'GNRH2' 176
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'SULT1A2' 177
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'RBP2' 178
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'GSTA1' 179
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'AFP' 180
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'APOC2' 181
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'FGA' 182
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'APOA4' 183
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'FABP1' 184
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'RBP4' 185
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'UGT2B11' 186
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'FGB' 187
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'TTR' 188
./prog_seq 'geneNames_3.txt' 'exe_9' 'hHep' 'FGG' 189
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'APOB' 190
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'GSTA2' 191
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'ALB' 192
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'HGD' 193
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'VTN' 194
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'APOC4.APOC2' 195
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'APOC3' 196
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'GNRH2' 197
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'SULT1A2' 198
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'RBP2' 199
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'GSTA1' 200
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'AFP' 201
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'APOC2' 202
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'FGA' 203
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'APOA4' 204
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'FABP1' 205
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'RBP4' 206
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'UGT2B11' 207
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'FGB' 208
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'TTR' 209
./prog_seq 'geneNames_3.txt' 'exe_10' 'hHep' 'FGG' 210
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'APOB' 211
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'GSTA2' 212
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'ALB' 213
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'HGD' 214
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'VTN' 215
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'APOC4.APOC2' 216
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'APOC3' 217
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'GNRH2' 218
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'SULT1A2' 219
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'RBP2' 220
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'GSTA1' 221
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'AFP' 222
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'APOC2' 223
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'FGA' 224
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'APOA4' 225
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'FABP1' 226
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'RBP4' 227
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'UGT2B11' 228
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'FGB' 229
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'TTR' 230
./prog_seq 'geneNames_3.txt' 'exe_11' 'hHep' 'FGG' 231
